### ISSUE TITLE
Swift 4 Compatibility

### ISSUE THREAD

**Issue by pieterclaerhout** [piwik/piwik-sdk-ios#183]
When trying this as a cocoapod in Xcode 9 using Swift 4, compiling fails with the following error:

```
<project>/Pods/PiwikTracker/PiwikTracker/PiwikTracker.swift:202:89: Struct 'MemoryQueue' is internal and cannot be referenced from a default argument value
```

Is this library supposed to be compatible with Swift 4 or do we need to use a specific branch?

**Comment by brototyp** [comment]
Hi @pieterclaerhout,

thanks for asking. You are totally right. We haven't added Swift 4 Compatibility yet. I just checked what is necessary to change and pushed a compatible version to this branch [swift-4](https://github.com/piwik/piwik-sdk-ios/tree/feature/swift-4). Please try and let me know if you encounter any issues.

**Comment by Shukuyen** [comment]
Works for me!

**Comment by brototyp** [comment]
Hi @Shukuyen, thanks for your reply. I just fixed the carthage build error. Once the build completed I will merge it. I will close this issue once it is released.

**Comment by BernhardWebstudio** [comment]
I am still getting this error in a newly installed instance - is the fix already public? Also, I am getting another warning: `Argument of '#selector' refers to instance method 'dispatch()' that is not exposed to Objective-C` for which a fix is recommended (`Add '@objc' to expose this instance method to Objective-C`). As I don't want to edit the file itself as it would be overriden with the next update I wonder whether I need to open a new pull request, and if the update will be relased soon?

**Comment by brototyp** [comment]
Hi @BernhardWebstudio, thanks for bringing this up. Unfortunately i merged it into the wrong branch 🤦‍♂️ 
I will merge it into the development branch and release a patch version right away.

For the warning: It would be great if you create a PR for it.

**Comment by brototyp** [comment]
I checked the issue. I am not sure why it isn't working for you. It is released in Version 4.2.0 and I just checked in the iOS Example Application if it works. Can you check if you use the latest version?

**Comment by BernhardWebstudio** [comment]
I was using 4.1.0 as this is still the default version loaded by CocoadPods and referenced in the README. By specifiyng 4.2.0 as the desired version, it is working as expected. Thank you for the support and sorry for bothering.

**Comment by brototyp** [comment]
Oh, sorry. The 4.1 in the README was irritating.
