### ISSUE TITLE
Device information and operating system not being tracked

### ISSUE THREAD

**Issue by ThomasGoehringer** [piwik/piwik-sdk-ios#329]
I just migrated from 5.x to 7.2 of MatomoTracker and now all device information and the operating system are not tracked anymore.
Am I missing any important code changes? Because I did not change any of my code.

**Comment by brototyp** [comment]
Hi @ThomasGoehringer, thanks for the question. I was away for some longer holidays and just got time to check that.

Are you sure you updated to 7.2? There was a bug in <7.2 (see #322) that resulted in exactly that problem but should be fixed in 7.2

**Comment by ThomasGoehringer** [comment]
Yes, I'm sure. My Podfile defines `pod 'MatomoTracker', '~> 7.2'`.

**Comment by SSenocico** [comment]
Not fixed.
From iOS SDK is tracked as **Unknown**

![Screenshot 2020-03-16 at 15 31 35](https://user-images.githubusercontent.com/60232541/76763167-439a5100-679b-11ea-9231-af8219b60940.png)

**Comment by brototyp** [comment]
Hi @ThomasGoehringer and @SSenocico, thanks for the followup. I think I know the problem now. It looks like the problem that you are encountering is that it takes some time to generate the `UserAgent` for the current device which we then use to send the events. I just benchmarked it and at least in one circumstance it took about 0,5 seconds to do so.

Can you do me a favor to confirm my suspicion? 

* Make sure an instance of the `MatomoTracker` is created
* Wait for ~2 seconds
* Track an event and dispatch it
* Check if that results in the correct behavior on the backen

**Comment by brototyp** [comment]
One more idea. If that doesn't work please try to `import WebKit` somewhere in your codebase to see if that changes anything. 

Thanks a lot upfront!

**Comment by ThomasGoehringer** [comment]
Sorry, none of those worked. Can you confirm, @SSenocico?
I only wrapped my code for event tracking inside
```
DispatchQueue.main.asyncAfter(deadline: .now() + 2.0) {

}
```
Is that what you wanted me to try?

**Comment by SSenocico** [comment]
@ThomasGoehringer Yes, I can confirm that it is the same for me.

**Comment by brototyp** [comment]
Thanks a lot for getting back to me and helping me understanding this problem.
I just pushed a special branch with some special logging. Maybe that helps to nail down the problem.

Can you do me a favor and, just for testing, install Matomo from the `bugfix/329-missing-device-info` branch. Also please setup verbose logging right after instantiating the Matomo instance like so: `matomoTracker.logger = DefaultLogger(minLevel: .verbose)`

Then please make sure an event is created and it's eventually dispatched.

I am curious to have a look at the log. Feel free do redact a server url or other information. It should look something like this:
```
MatomoTracker [V] Queued event: Event(uuid: 2F8616EA-D143-43C3-B65E-BD15538909EE, siteId: "23", visitor: MatomoTracker.Visitor(id: "A6AD6BC7089246C0", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 14, lastVisit: 2020-05-03 13:46:12 +0000, firstVisit: 2020-04-05 10:01:06 +0000), date: 2020-05-03 13:46:34 +0000, url: Optional(http://org.matomo.iostracker/menu), actionName: ["menu"], language: "en;q=1.0,de-AT;q=0.9", isNewSession: true, referer: nil, screenResolution: (320.0, 568.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil)
MatomoTracker [D] userAgent generated: Mozilla/5.0 (x86_64; CPU iPhone OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 MatomoTracker SDK URLSessionDispatcher
MatomoTracker [V] Queued event: Event(uuid: B3A1960C-8AAF-4889-85EB-B8982AAE047D, siteId: "23", visitor: MatomoTracker.Visitor(id: "A6AD6BC7089246C0", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 14, lastVisit: 2020-05-03 13:46:12 +0000, firstVisit: 2020-04-05 10:01:06 +0000), date: 2020-05-03 13:46:40 +0000, url: Optional(http://org.matomo.iostracker/menu/configuration), actionName: ["menu", "configuration"], language: "en;q=1.0,de-AT;q=0.9", isNewSession: false, referer: nil, screenResolution: (320.0, 568.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil)
MatomoTracker [I] Start dispatching events
MatomoTracker [V] Sending events [MatomoTracker.Event(uuid: 2F8616EA-D143-43C3-B65E-BD15538909EE, siteId: "23", visitor: MatomoTracker.Visitor(id: "A6AD6BC7089246C0", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 14, lastVisit: 2020-05-03 13:46:12 +0000, firstVisit: 2020-04-05 10:01:06 +0000), date: 2020-05-03 13:46:34 +0000, url: Optional(http://org.matomo.iostracker/menu), actionName: ["menu"], language: "en;q=1.0,de-AT;q=0.9", isNewSession: true, referer: nil, screenResolution: (320.0, 568.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil), MatomoTracker.Event(uuid: B3A1960C-8AAF-4889-85EB-B8982AAE047D, siteId: "23", visitor: MatomoTracker.Visitor(id: "A6AD6BC7089246C0", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 14, lastVisit: 2020-05-03 13:46:12 +0000, firstVisit: 2020-04-05 10:01:06 +0000), date: 2020-05-03 13:46:40 +0000, url: Optional(http://org.matomo.iostracker/menu/configuration), actionName: ["menu", "configuration"], language: "en;q=1.0,de-AT;q=0.9", isNewSession: false, referer: nil, screenResolution: (320.0, 568.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil)] to Optional(https://demo2.matomo.org/piwik.php) with header Optional(["Content-Type": "application/json; charset=utf-8", "User-Agent": "Mozilla/5.0 (x86_64; CPU iPhone OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 MatomoTracker SDK URLSessionDispatcher"])
MatomoTracker [I] Dispatched batch of 2 events.
MatomoTracker [I] Finished dispatching events
```

**Comment by SSenocico** [comment]
Hi @brototyp 
I did as you mentioned.

The logs are:

```
MatomoTracker [V] Queued event: Event(uuid: 5D54A1C9-62F6-4E71-928D-3252CE3BAE4B, siteId: "1", visitor: MatomoTracker.Visitor(id: "B1AFCD00C2864953", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 35, lastVisit: 2020-05-04 07:19:04 +0000, firstVisit: 2020-04-15 14:07:17 +0000), date: 2020-05-04 07:40:35 +0000, url: Optional(http://com.english-attack.qioz/languagesVC), actionName: ["languagesVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil)
MatomoTracker [V] Queued event: Event(uuid: 131952DD-30F6-4864-8C87-CB675C596336, siteId: "60", visitor: MatomoTracker.Visitor(id: "815B547CFB1C4C4F", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 35, lastVisit: 2020-05-04 07:19:04 +0000, firstVisit: 2020-04-15 14:07:17 +0000), date: 2020-05-04 07:40:35 +0000, url: Optional(http://com.english-attack.qioz/languagesVC), actionName: ["languagesVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil)
MatomoTracker [I] Start dispatching events
MatomoTracker [V] Sending events [MatomoTracker.Event(uuid: EC9BA710-F619-4D6B-B696-B8327AC1D59D, siteId: "1", visitor: MatomoTracker.Visitor(id: "B1AFCD00C2864953", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 35, lastVisit: 2020-05-04 07:19:04 +0000, firstVisit: 2020-04-15 14:07:17 +0000), date: 2020-05-04 07:40:13 +0000, url: Optional(http://com.english-attack.qioz/moreVC), actionName: ["moreVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil), MatomoTracker.Event(uuid: AD65DDD9-4839-4B0D-831A-77EECFFA0FB6, siteId: "1", visitor: MatomoTracker.Visitor(id: "B1AFCD00C2864953", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 35, lastVisit: 2020-05-04 07:19:04 +0000, firstVisit: 2020-04-15 14:07:17 +0000), date: 2020-05-04 07:40:13 +0000, url: Optional(http://com.english-attack.qioz/assessmentTestVC), actionName: ["assessmentTestVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil), MatomoTracker.Event(uuid: 2883A8A4-192C-4B92-9EE3-3ACD960042A0, siteId: "1", visitor: MatomoTracker.Visitor(id: "B1AFCD00C2864953", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 35, lastVisit: 2020-05-04 07:19:04 +0000, firstVisit: 2020-04-15 14:07:17 +0000), date: 2020-05-04 07:40:13 +0000, url: Optional(http://com.english-attack.qioz/currentTestsAssessmentVC), actionName: ["currentTestsAssessmentVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil), MatomoTracker.Event(uuid: ABD119C6-56CB-4CD4-8F7C-CCA052C081BC, siteId: "1", visitor: MatomoTracker.Visitor(id: "B1AFCD00C2864953", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 35, lastVisit: 2020-05-04 07:19:04 +0000, firstVisit: 2020-04-15 14:07:17 +0000), date: 2020-05-04 07:40:13 +0000, url: Optional(http://com.english-attack.qioz/pastTestsAssessmentVC), actionName: ["pastTestsAssessmentVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil), MatomoTracker.Event(uuid: B501F456-93D4-49D2-8843-2A0278A7B931, siteId: "1", visitor: MatomoTracker.Visitor(id: "B1AFCD00C2864953", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 35, lastVisit: 2020-05-04 07:19:04 +0000, firstVisit: 2020-04-15 14:07:17 +0000), date: 2020-05-04 07:40:16 +0000, url: Optional(http://com.english-attack.qioz/accountProfileVC), actionName: ["accountProfileVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil), MatomoTracker.Event(uuid: A4340511-8030-4677-8D5F-E0F66B996DA4, siteId: "1", visitor: MatomoTracker.Visitor(id: "B1AFCD00C2864953", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 35, lastVisit: 2020-05-04 07:19:04 +0000, firstVisit: 2020-04-15 14:07:17 +0000), date: 2020-05-04 07:40:21 +0000, url: Optional(http://com.english-attack.qioz/supportVC), actionName: ["supportVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil), MatomoTracker.Event(uuid: 5D54A1C9-62F6-4E71-928D-3252CE3BAE4B, siteId: "1", visitor: MatomoTracker.Visitor(id: "B1AFCD00C2864953", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 35, lastVisit: 2020-05-04 07:19:04 +0000, firstVisit: 2020-04-15 14:07:17 +0000), date: 2020-05-04 07:40:35 +0000, url: Optional(http://com.english-attack.qioz/languagesVC), actionName: ["languagesVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil)] to Optional(https://qioz.matomo.cloud/matomo.php) with header Optional(["Content-Type": "application/json; charset=utf-8", "User-Agent": " MatomoTracker SDK URLSessionDispatcher"])
MatomoTracker [I] Dispatched batch of 7 events.
MatomoTracker [I] Finished dispatching events
MatomoTracker [I] Start dispatching events
MatomoTracker [V] Sending events [MatomoTracker.Event(uuid: 16AF14A7-352E-4727-9759-857D31C041B3, siteId: "60", visitor: MatomoTracker.Visitor(id: "815B547CFB1C4C4F", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 35, lastVisit: 2020-05-04 07:19:04 +0000, firstVisit: 2020-04-15 14:07:17 +0000), date: 2020-05-04 07:40:13 +0000, url: Optional(http://com.english-attack.qioz/moreVC), actionName: ["moreVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil), MatomoTracker.Event(uuid: B40AC8D1-42D8-485D-B0BE-48E1B55E12C3, siteId: "60", visitor: MatomoTracker.Visitor(id: "815B547CFB1C4C4F", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 35, lastVisit: 2020-05-04 07:19:04 +0000, firstVisit: 2020-04-15 14:07:17 +0000), date: 2020-05-04 07:40:13 +0000, url: Optional(http://com.english-attack.qioz/assessmentTestVC), actionName: ["assessmentTestVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil), MatomoTracker.Event(uuid: EB96A4F0-DC62-4D58-9C99-8854CC779D91, siteId: "60", visitor: MatomoTracker.Visitor(id: "815B547CFB1C4C4F", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 35, lastVisit: 2020-05-04 07:19:04 +0000, firstVisit: 2020-04-15 14:07:17 +0000), date: 2020-05-04 07:40:13 +0000, url: Optional(http://com.english-attack.qioz/currentTestsAssessmentVC), actionName: ["currentTestsAssessmentVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil), MatomoTracker.Event(uuid: B9D58A1F-574B-423D-9767-FA9AD8D7B46C, siteId: "60", visitor: MatomoTracker.Visitor(id: "815B547CFB1C4C4F", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 35, lastVisit: 2020-05-04 07:19:04 +0000, firstVisit: 2020-04-15 14:07:17 +0000), date: 2020-05-04 07:40:13 +0000, url: Optional(http://com.english-attack.qioz/pastTestsAssessmentVC), actionName: ["pastTestsAssessmentVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil), MatomoTracker.Event(uuid: D3807B13-FB06-406C-B5FC-39D15F985C5E, siteId: "60", visitor: MatomoTracker.Visitor(id: "815B547CFB1C4C4F", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 35, lastVisit: 2020-05-04 07:19:04 +0000, firstVisit: 2020-04-15 14:07:17 +0000), date: 2020-05-04 07:40:16 +0000, url: Optional(http://com.english-attack.qioz/accountProfileVC), actionName: ["accountProfileVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil), MatomoTracker.Event(uuid: 5F55E9B4-57A3-450D-95BB-C7B9AB06D53F, siteId: "60", visitor: MatomoTracker.Visitor(id: "815B547CFB1C4C4F", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 35, lastVisit: 2020-05-04 07:19:04 +0000, firstVisit: 2020-04-15 14:07:17 +0000), date: 2020-05-04 07:40:21 +0000, url: Optional(http://com.english-attack.qioz/supportVC), actionName: ["supportVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil), MatomoTracker.Event(uuid: 131952DD-30F6-4864-8C87-CB675C596336, siteId: "60", visitor: MatomoTracker.Visitor(id: "815B547CFB1C4C4F", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 35, lastVisit: 2020-05-04 07:19:04 +0000, firstVisit: 2020-04-15 14:07:17 +0000), date: 2020-05-04 07:40:35 +0000, url: Optional(http://com.english-attack.qioz/languagesVC), actionName: ["languagesVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil)] to Optional(https://stats.iledefrance.fr/matomo.php) with header Optional(["User-Agent": " MatomoTracker SDK URLSessionDispatcher", "Content-Type": "application/json; charset=utf-8"])
MatomoTracker [I] Dispatched batch of 7 events.
MatomoTracker [I] Finished dispatching events
MatomoTracker [I] No need to dispatch. Dispatch queue is empty.
```
![Screenshot 2020-05-04 at 10 46 21](https://user-images.githubusercontent.com/60232541/80945448-83250700-8df4-11ea-8af0-f82c99262bab.png)

**Comment by brototyp** [comment]
Thanks a lot @SSenocico, that helps! I can see we are missing the `MatomoTracker [D] userAgent generated:` line, so it falls back to just our prefix.

Does the project override the user agent some how?

I'll add some more logs and we can go for another round of testing here. I think we are slowly inching forward.

**Comment by ThomasGoehringer** [comment]
My log looks the same with the userAgent line missing.

**Comment by SSenocico** [comment]
@brototyp 

> Does the project override the user agent some how?

No, not at all.

**Comment by brototyp** [comment]
Alright. I added a few more logs to the custom branch. Can you try the same again?

**Comment by SSenocico** [comment]
@brototyp 
These are the new logs:

```
MatomoTracker [I] Start dispatching events
MatomoTracker [V] Sending events [MatomoTracker.Event(uuid: 00C0CFFF-62E7-4B13-9879-6492FEBE8191, siteId: "1", visitor: MatomoTracker.Visitor(id: "33B1B3BB2EA84982", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 19, lastVisit: 2020-05-11 07:52:54 +0000, firstVisit: 2020-05-07 09:17:26 +0000), date: 2020-05-11 09:49:10 +0000, url: Optional(http://com.english-attack.qioz/tabBarVC), actionName: ["tabBarVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: true, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil), MatomoTracker.Event(uuid: 6F54108A-B11C-4283-B761-F82611527E59, siteId: "1", visitor: MatomoTracker.Visitor(id: "33B1B3BB2EA84982", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 19, lastVisit: 2020-05-11 07:52:54 +0000, firstVisit: 2020-05-07 09:17:26 +0000), date: 2020-05-11 09:49:10 +0000, url: Optional(http://com.english-attack.qioz/homeVC), actionName: ["homeVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil), MatomoTracker.Event(uuid: 6CF42CBD-1996-40A4-A00C-120498D7B15E, siteId: "1", visitor: MatomoTracker.Visitor(id: "33B1B3BB2EA84982", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 19, lastVisit: 2020-05-11 07:52:54 +0000, firstVisit: 2020-05-07 09:17:26 +0000), date: 2020-05-11 09:49:35 +0000, url: Optional(http://com.english-attack.qioz/moreVC), actionName: ["moreVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil), MatomoTracker.Event(uuid: 68033B6B-23A6-4B4B-9177-765B3C94D857, siteId: "1", visitor: MatomoTracker.Visitor(id: "33B1B3BB2EA84982", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 19, lastVisit: 2020-05-11 07:52:54 +0000, firstVisit: 2020-05-07 09:17:26 +0000), date: 2020-05-11 09:49:35 +0000, url: Optional(http://com.english-attack.qioz/assessmentTestVC), actionName: ["assessmentTestVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil), MatomoTracker.Event(uuid: B6E7F993-39D1-4CDC-ACDD-39D20C3A0AD0, siteId: "1", visitor: MatomoTracker.Visitor(id: "33B1B3BB2EA84982", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 19, lastVisit: 2020-05-11 07:52:54 +0000, firstVisit: 2020-05-07 09:17:26 +0000), date: 2020-05-11 09:49:35 +0000, url: Optional(http://com.english-attack.qioz/currentTestsAssessmentVC), actionName: ["currentTestsAssessmentVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil), MatomoTracker.Event(uuid: 9E6E284D-744F-4667-8356-D60B8325D667, siteId: "1", visitor: MatomoTracker.Visitor(id: "33B1B3BB2EA84982", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 19, lastVisit: 2020-05-11 07:52:54 +0000, firstVisit: 2020-05-07 09:17:26 +0000), date: 2020-05-11 09:49:35 +0000, url: Optional(http://com.english-attack.qioz/pastTestsAssessmentVC), actionName: ["pastTestsAssessmentVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil), MatomoTracker.Event(uuid: D99A65CA-8F14-445C-8290-052906A75760, siteId: "1", visitor: MatomoTracker.Visitor(id: "33B1B3BB2EA84982", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 19, lastVisit: 2020-05-11 07:52:54 +0000, firstVisit: 2020-05-07 09:17:26 +0000), date: 2020-05-11 09:49:37 +0000, url: Optional(http://com.english-attack.qioz/accountProfileVC), actionName: ["accountProfileVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil)] to Optional(https://qioz.matomo.cloud/matomo.php) with header Optional(["User-Agent": "Mozilla/5.0 (x86_64; CPU iPhone OS 13_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 MatomoTracker SDK URLSessionDispatcher", "Content-Type": "application/json; charset=utf-8"])
MatomoTracker [I] Start dispatching events
MatomoTracker [V] Sending events [MatomoTracker.Event(uuid: 1A7AFB53-E8C0-458C-B17C-9086AB85213B, siteId: "60", visitor: MatomoTracker.Visitor(id: "E626EB4958784CEC", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 19, lastVisit: 2020-05-11 07:52:54 +0000, firstVisit: 2020-05-07 09:17:26 +0000), date: 2020-05-11 09:49:10 +0000, url: Optional(http://com.english-attack.qioz/tabBarVC), actionName: ["tabBarVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: true, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil), MatomoTracker.Event(uuid: 0F5426BC-3028-4CA4-9010-87F91EE6234D, siteId: "60", visitor: MatomoTracker.Visitor(id: "E626EB4958784CEC", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 19, lastVisit: 2020-05-11 07:52:54 +0000, firstVisit: 2020-05-07 09:17:26 +0000), date: 2020-05-11 09:49:10 +0000, url: Optional(http://com.english-attack.qioz/homeVC), actionName: ["homeVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil), MatomoTracker.Event(uuid: F585325A-7C6F-419D-9786-FF6F6C9594E7, siteId: "60", visitor: MatomoTracker.Visitor(id: "E626EB4958784CEC", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 19, lastVisit: 2020-05-11 07:52:54 +0000, firstVisit: 2020-05-07 09:17:26 +0000), date: 2020-05-11 09:49:35 +0000, url: Optional(http://com.english-attack.qioz/moreVC), actionName: ["moreVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil), MatomoTracker.Event(uuid: B31823FD-52E4-4FF2-B583-4D422AF140D8, siteId: "60", visitor: MatomoTracker.Visitor(id: "E626EB4958784CEC", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 19, lastVisit: 2020-05-11 07:52:54 +0000, firstVisit: 2020-05-07 09:17:26 +0000), date: 2020-05-11 09:49:35 +0000, url: Optional(http://com.english-attack.qioz/assessmentTestVC), actionName: ["assessmentTestVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil), MatomoTracker.Event(uuid: D9314507-32C4-426B-A5A3-FB7ED3D6C278, siteId: "60", visitor: MatomoTracker.Visitor(id: "E626EB4958784CEC", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 19, lastVisit: 2020-05-11 07:52:54 +0000, firstVisit: 2020-05-07 09:17:26 +0000), date: 2020-05-11 09:49:35 +0000, url: Optional(http://com.english-attack.qioz/currentTestsAssessmentVC), actionName: ["currentTestsAssessmentVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil), MatomoTracker.Event(uuid: 7A3C54A8-07C8-493D-901E-E0E933D86B30, siteId: "60", visitor: MatomoTracker.Visitor(id: "E626EB4958784CEC", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 19, lastVisit: 2020-05-11 07:52:54 +0000, firstVisit: 2020-05-07 09:17:26 +0000), date: 2020-05-11 09:49:35 +0000, url: Optional(http://com.english-attack.qioz/pastTestsAssessmentVC), actionName: ["pastTestsAssessmentVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil), MatomoTracker.Event(uuid: 0CB80596-984B-49DD-AE31-C407F05E8F8F, siteId: "60", visitor: MatomoTracker.Visitor(id: "E626EB4958784CEC", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 19, lastVisit: 2020-05-11 07:52:54 +0000, firstVisit: 2020-05-07 09:17:26 +0000), date: 2020-05-11 09:49:37 +0000, url: Optional(http://com.english-attack.qioz/accountProfileVC), actionName: ["accountProfileVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil)] to Optional(https://stats.iledefrance.fr/matomo.php) with header Optional(["User-Agent": "Mozilla/5.0 (x86_64; CPU iPhone OS 13_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 MatomoTracker SDK URLSessionDispatcher", "Content-Type": "application/json; charset=utf-8"])
MatomoTracker [I] Dispatched batch of 7 events.
MatomoTracker [I] Finished dispatching events
MatomoTracker [I] Dispatched batch of 7 events.
MatomoTracker [I] Finished dispatching events
```

**Comment by brototyp** [comment]
That's interesting. Now there is a proper userAgent in these requests. Can you check if this worked on the backend side and if you now got the information there?
I am not sure why it worked this time though. Still something we have to figure out.

**Comment by jigar007** [comment]
@brototyp I am having the same issue. UserAgent is missing in my logs.
I tried bugfix/329-missing-device-info and still can't find the user agent in log.

**Comment by brototyp** [comment]
> @brototyp I am having the same issue. UserAgent is missing in my logs.
> I tried bugfix/329-missing-device-info and still can't find the user agent in log.

Can you please attach your logs?

**Comment by SSenocico** [comment]
@brototyp  Seems that now it appears:

![Screenshot 2020-05-11 at 14 17 17](https://user-images.githubusercontent.com/60232541/81555950-23010880-9392-11ea-8942-4bade3167a05.png)

Other logs:

```
MatomoTracker [V] Queued event: Event(uuid: A92510A1-771F-49B3-B829-98DDBF303BB4, siteId: "1", visitor: MatomoTracker.Visitor(id: "33B1B3BB2EA84982", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 27, lastVisit: 2020-05-11 10:12:10 +0000, firstVisit: 2020-05-07 09:17:26 +0000), date: 2020-05-11 11:14:28 +0000, url: Optional(http://com.english-attack.qioz/exercisesVC), actionName: ["exercisesVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil)
MatomoTracker [V] Queued event: Event(uuid: 9DFDE1EE-5A92-41A4-8123-44D64B52FACE, siteId: "60", visitor: MatomoTracker.Visitor(id: "E626EB4958784CEC", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 27, lastVisit: 2020-05-11 10:12:10 +0000, firstVisit: 2020-05-07 09:17:26 +0000), date: 2020-05-11 11:14:28 +0000, url: Optional(http://com.english-attack.qioz/exercisesVC), actionName: ["exercisesVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil)
MatomoTracker [V] Queued event: Event(uuid: 9F0362B9-72E1-4ABA-9AC1-0CB67252C14A, siteId: "1", visitor: MatomoTracker.Visitor(id: "33B1B3BB2EA84982", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 27, lastVisit: 2020-05-11 10:12:10 +0000, firstVisit: 2020-05-07 09:17:26 +0000), date: 2020-05-11 11:14:28 +0000, url: Optional(http://com.english-attack.qioz/vocabQuickViewVC), actionName: ["vocabQuickViewVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil)
MatomoTracker [V] Queued event: Event(uuid: 14B91FB1-A5B0-4DF3-89B9-E16C55BA92EF, siteId: "60", visitor: MatomoTracker.Visitor(id: "E626EB4958784CEC", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 27, lastVisit: 2020-05-11 10:12:10 +0000, firstVisit: 2020-05-07 09:17:26 +0000), date: 2020-05-11 11:14:28 +0000, url: Optional(http://com.english-attack.qioz/vocabQuickViewVC), actionName: ["vocabQuickViewVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil)
2020-05-11 14:14:28.145469+0300 QIOZ[8808:206757] <CATransformLayer: 0x600001bd0f40> - changing property contentsGravity in transform-only layer, will have no effect
MatomoTracker [I] Start dispatching events
MatomoTracker [V] Sending events [MatomoTracker.Event(uuid: 0D66DBD1-77F0-4C0A-92B7-468C91197140, siteId: "1", visitor: MatomoTracker.Visitor(id: "33B1B3BB2EA84982", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 27, lastVisit: 2020-05-11 10:12:10 +0000, firstVisit: 2020-05-07 09:17:26 +0000), date: 2020-05-11 11:14:20 +0000, url: Optional(http://com.english-attack.qioz/albumVC), actionName: ["albumVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil), MatomoTracker.Event(uuid: B7D7D422-E696-44FF-8094-CF36AF614D13, siteId: "1", visitor: MatomoTracker.Visitor(id: "33B1B3BB2EA84982", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 27, lastVisit: 2020-05-11 10:12:10 +0000, firstVisit: 2020-05-07 09:17:26 +0000), date: 2020-05-11 11:14:22 +0000, url: Optional(http://com.english-attack.qioz/catalogVCNav), actionName: ["catalogVCNav"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil), MatomoTracker.Event(uuid: 4BF8B7D2-8214-4EFB-B06E-BBFE5014E2B7, siteId: "1", visitor: MatomoTracker.Visitor(id: "33B1B3BB2EA84982", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 27, lastVisit: 2020-05-11 10:12:10 +0000, firstVisit: 2020-05-07 09:17:26 +0000), date: 2020-05-11 11:14:26 +0000, url: Optional(http://com.english-attack.qioz/videoBoosterPreviewVC), actionName: ["videoBoosterPreviewVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil), MatomoTracker.Event(uuid: A92510A1-771F-49B3-B829-98DDBF303BB4, siteId: "1", visitor: MatomoTracker.Visitor(id: "33B1B3BB2EA84982", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 27, lastVisit: 2020-05-11 10:12:10 +0000, firstVisit: 2020-05-07 09:17:26 +0000), date: 2020-05-11 11:14:28 +0000, url: Optional(http://com.english-attack.qioz/exercisesVC), actionName: ["exercisesVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil), MatomoTracker.Event(uuid: 9F0362B9-72E1-4ABA-9AC1-0CB67252C14A, siteId: "1", visitor: MatomoTracker.Visitor(id: "33B1B3BB2EA84982", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 27, lastVisit: 2020-05-11 10:12:10 +0000, firstVisit: 2020-05-07 09:17:26 +0000), date: 2020-05-11 11:14:28 +0000, url: Optional(http://com.english-attack.qioz/vocabQuickViewVC), actionName: ["vocabQuickViewVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil)] to Optional(https://qioz.matomo.cloud/matomo.php) with header Optional(["Content-Type": "application/json; charset=utf-8", "User-Agent": "Mozilla/5.0 (x86_64; CPU iPhone OS 13_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 MatomoTracker SDK URLSessionDispatcher"])
MatomoTracker [I] Start dispatching events
MatomoTracker [V] Sending events [MatomoTracker.Event(uuid: 4F739988-4432-4C41-9967-7B8E28773ECF, siteId: "60", visitor: MatomoTracker.Visitor(id: "E626EB4958784CEC", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 27, lastVisit: 2020-05-11 10:12:10 +0000, firstVisit: 2020-05-07 09:17:26 +0000), date: 2020-05-11 11:14:20 +0000, url: Optional(http://com.english-attack.qioz/albumVC), actionName: ["albumVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil), MatomoTracker.Event(uuid: CC56ABBA-F9AE-4520-934B-11507F756918, siteId: "60", visitor: MatomoTracker.Visitor(id: "E626EB4958784CEC", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 27, lastVisit: 2020-05-11 10:12:10 +0000, firstVisit: 2020-05-07 09:17:26 +0000), date: 2020-05-11 11:14:23 +0000, url: Optional(http://com.english-attack.qioz/catalogVCNav), actionName: ["catalogVCNav"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil), MatomoTracker.Event(uuid: 9C1A4974-7B69-49B2-A28E-A9DD3081CA36, siteId: "60", visitor: MatomoTracker.Visitor(id: "E626EB4958784CEC", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 27, lastVisit: 2020-05-11 10:12:10 +0000, firstVisit: 2020-05-07 09:17:26 +0000), date: 2020-05-11 11:14:26 +0000, url: Optional(http://com.english-attack.qioz/videoBoosterPreviewVC), actionName: ["videoBoosterPreviewVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil), MatomoTracker.Event(uuid: 9DFDE1EE-5A92-41A4-8123-44D64B52FACE, siteId: "60", visitor: MatomoTracker.Visitor(id: "E626EB4958784CEC", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 27, lastVisit: 2020-05-11 10:12:10 +0000, firstVisit: 2020-05-07 09:17:26 +0000), date: 2020-05-11 11:14:28 +0000, url: Optional(http://com.english-attack.qioz/exercisesVC), actionName: ["exercisesVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil), MatomoTracker.Event(uuid: 14B91FB1-A5B0-4DF3-89B9-E16C55BA92EF, siteId: "60", visitor: MatomoTracker.Visitor(id: "E626EB4958784CEC", forcedId: nil, userId: nil), session: MatomoTracker.Session(sessionsCount: 27, lastVisit: 2020-05-11 10:12:10 +0000, firstVisit: 2020-05-07 09:17:26 +0000), date: 2020-05-11 11:14:28 +0000, url: Optional(http://com.english-attack.qioz/vocabQuickViewVC), actionName: ["vocabQuickViewVC"], language: "en;q=1.0,ro-RO;q=0.9", isNewSession: false, referer: nil, screenResolution: (414.0, 896.0), customVariables: [], eventCategory: nil, eventAction: nil, eventName: nil, eventValue: nil, campaignName: nil, campaignKeyword: nil, searchQuery: nil, searchCategory: nil, searchResultsCount: nil, dimensions: [], customTrackingParameters: [:], contentName: nil, contentPiece: nil, contentTarget: nil, contentInteraction: nil, goalId: nil, revenue: nil, orderId: nil, orderItems: [], orderRevenue: nil, orderSubTotal: nil, orderTax: nil, orderShippingCost: nil, orderDiscount: nil, orderLastDate: nil)] to Optional(https://stats.iledefrance.fr/matomo.php) with header Optional(["Content-Type": "application/json; charset=utf-8", "User-Agent": "Mozilla/5.0 (x86_64; CPU iPhone OS 13_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 MatomoTracker SDK URLSessionDispatcher"])
MatomoTracker [I] Dispatched batch of 5 events.
MatomoTracker [I] Finished dispatching events
MatomoTracker [I] Dispatched batch of 5 events.
MatomoTracker [I] Finished dispatching events
```

**Comment by jigar007** [comment]
@brototyp  Here is the log related to matomo:
MatomoTracker [I] Start dispatching events
MatomoTracker [I] Dispatched batch of 1 events.2020-05-11 21:15:52.179467+1000 
MatomoTracker [I] Finished dispatching events
MatomoTracker [I] No need to dispatch. Dispatch queue is empty.
MatomoTracker [I] No need to dispatch. Dispatch queue is empty.
MatomoTracker [I] No need to dispatch. Dispatch queue is empty.

Actually, I have just added Matomo to my app and still exploring docs, but getting useragent and up and running is at most priority. (I mean device and os detection in matomo cloud)

**Comment by jigar007** [comment]
@brototyp It seems there is some threading issue (in the callback of user agent setting), I have tried to debug it using breakpoints. 

I have added '7.0.1' and it is working fine now.

**Comment by brototyp** [comment]
Hey @SSenocico, thanks for your effort in debugging this issue together with me. I updated the `bugfix/329-missing-device-info` branch once again and removed most of the logging. Can you have one more try on that one? If it works, I think we found the issue for this bug \o/

**Comment by SSenocico** [comment]
I tested it again and it all seems to work fine. I checked the dashboard and all the events are there. From my side, I confirm that this issue is now resolved 🥳🎉

**Comment by ThomasGoehringer** [comment]
~~How fast should the device information appear?~~

Alright, I can confirm the issue as resolved, too.

**Comment by brototyp** [comment]
Thanks a lot! That was a tricky thing to find out.

**Comment by brototyp** [comment]
Alright. This is merged and will be part of the next release. Thanks for the help!
