### ISSUE TITLE
Bug - Device detection attributes +80% of iOS visits as Phablet

### ISSUE THREAD

**Issue by atom-box** [piwik/piwik-sdk-ios#451]
The iOS SDK seems to over-attribute the device type as phablet.  
Notice the very different rates for phablet data from three different sources:

1. Using the iOS SDK for an app 
88% phablet
![device-type1](https://github.com/matomo-org/matomo-sdk-ios/assets/22874146/a17f4cfc-a39a-4541-9561-ab08414872e3)

2. Using the Android SDK for the Android version of the same app
9% phablet

3. Using Matomo for my desktop website
4% phablet
![inDesktop](https://github.com/matomo-org/matomo-sdk-ios/assets/22874146/def483b4-be1e-4bb2-a041-ff3496c939e9)

**Comment by atom-box** [comment]
This issue seems to have started on March 20 / 21. 
Here is the phablet detection rate over time:

![image](https://github.com/matomo-org/matomo-sdk-ios/assets/22874146/45c68188-c28e-491a-bc38-2a40fae0a273)
![image](https://github.com/matomo-org/matomo-sdk-ios/assets/22874146/794c0479-c669-4d89-af96-69ebbfa7446b)

(these screenshots are from a totally unrelated user, with a different Matomo server, than the screenshots in my first message, above)

**Comment by atom-box** [comment]
Maybe this is good easy first-issue for a contributor.
@brototyp is there a way to flag this as "easy starter issue"?

**Comment by brototyp** [comment]
Hey @atom-box, thanks for reporting this. I have the suspicion, that this is an issue serverside. What do you use as a backend? Your own hosted Matomo instance? Is it possible, that you updated that instance in March?

**Comment by brototyp** [comment]
Closing this for now. Please feel free to re-open the ticket if you think it still exists.

**Comment by PeteTrombone** [comment]
@brototyp : Why was this closed? The problem still exists!

**Comment by brototyp** [comment]
@PeteTrombone I closed this issue since it is stale. I cannot reproduce it from my side and nobody responded to debug together with me. So the only assumption left for me was that it probably is resolved.

**Comment by PeteTrombone** [comment]
@brototyp as I said, the problem still exists. Here is the proof:
![image](https://github.com/user-attachments/assets/456156c4-92f4-4f9c-b697-bcb60a1ab565)

@atom-box maybe you have some more examples that the problem has not yet been solved?

**Comment by brototyp** [comment]
I believe you, that it still exists. That fact alone does not help to debug it though. Do you have any information to help narrow down the issue?  

What do you use as a backend? Your own hosted Matomo instance or the Matomo-hosted one?

Can you correlate the appearance of this issue with an update of the backend or the SDK?

**Comment by brototyp** [comment]
@Findus23 Do you think this issue might be related to any changes in the https://github.com/matomo-org/device-detector ?
